# Generated by Django 5.1.3 on 2024-11-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "track_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("song_name", models.CharField(max_length=100)),
                ("artist_name", models.CharField(max_length=100)),
                ("album_name", models.CharField(max_length=100)),
                ("release_date", models.CharField(max_length=100)),
                ("popularity", models.IntegerField()),
                ("duration_ms", models.IntegerField()),
                ("preview_url", models.CharField(max_length=500)),
                ("album_image", models.CharField(max_length=500)),
            ],
        ),
    ]
