# Generated by Django 5.1.3 on 2024-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration_ms', models.IntegerField()),
                ('track_id', models.CharField(max_length=255)),
                ('album_image_url', models.URLField()),
            ],
        ),
    ]
